name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.4

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Build
      env:
        CGO_ENABLED: 0
      run: go build -v -o snyk-sso-membership cmd/snyk/main.go

    - name: Unit tests
      run: go test -v ./...
