name: Security

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * 0"

  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Setup Snyk scan
        uses: snyk/actions/setup@master

      - name: Runs Snyk Code
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
